version: "3.7"

services:
  database:
    image: "postgres"
    container_name: database_ifce
    restart: always
    expose:
      - 5433
    ports:
      - "5433:5433"
    environment:
      POSTGRES_USER: ifce_admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cantina_db
    volumes:
      - pgdata:/data/ifce/postgres
    command: -p 5433


  # app:
  #   build: .
  #   ports:
  #     - "9000:8080"
  #   environment:
  #     SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/cantinaDB
  #     SPRING_DATASOURCE_USERNAME: ifce_admin
  #     SPRING_DATASOURCE_PASSWORD: admin
  #   depends_on:
  #     - db

volumes:
  pgdata:
    driver: local
