version: "3.7"

services:
  database:
    env_file:
      - .env
    image: "postgres"
    container_name: sisref
    restart: always
    expose:
      - ${DOCKER_PORT_DATABASE}
    ports:
      - "${DOCKER_PORT_DATABASE}:${DOCKER_PORT_DATABASE}"
    environment:
      POSTGRES_USER: "${DOCKER_USER_DATABASE}"
      POSTGRES_PASSWORD: "${DOCKER_PASSWORD_DATABASE}"
      POSTGRES_DB: sisrefdb
    volumes:
      - pgdata:/data/ifce/postgres
    command: -p ${DOCKER_PORT_DATABASE}

volumes:
  pgdata:
    driver: local
