version: "3.7"

services:
  app:
      build: .
      container_name: sisref_api
      restart: always
      env_file:
        - .env
      ports:
        - 3333:3333
      volumes:
        - .:/app
      links:
        - database
      depends_on: 
        - database
      networks:
        - app-connect
  database:
    env_file:
      - .env
    image: "postgres"
    restart: always
    ports:
      - "5433:${DOCKER_PORT_DATABASE}"
    environment:
      POSTGRES_USER: "${DOCKER_USER_DATABASE}"
      POSTGRES_PASSWORD: "${DOCKER_PASSWORD_DATABASE}"
      POSTGRES_DB: sisrefdb
    volumes:
      - pgdata:/data/ifce/postgres
    command: -p ${DOCKER_PORT_DATABASE}
    networks:
      - app-connect
  
volumes:
  pgdata:
    driver: local

networks:
  app-connect:
      driver: bridge
